apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /  # 타켓 / 로 재정의
    # ingressclass.kubernetes.io/is-default-class: "true"  # 기본 인그레스 설정
spec:
  ingressClassName: nginx
  rules:
   - http:
      paths:
      - path: /api/hello1
        pathType: Exact
        backend:
          service:
            name: my-service-1
            port:
              number: 80
      - path: /api/hello2
        pathType: Exact
        backend:
          service:
            name: my-service-2
            port:
              number: 80
      - path: /api/hello3
        pathType: Exact
        backend:
          service:
            name: my-service-3
            port:
              number: 80
      - path: /api/hello4
        pathType: Exact
        backend:
          service:
            name: my-service-4
            port:
              number: 80
              