apiVersion: v1
kind: Service
metadata:
  name: my-service-4
spec:
  type: LoadBalancer
  selector:
    app: hello4
    version: v1
  ports:
    - protocol: TCP
      port: 8080         # 클러스터 IP에서 접근할 포트
      targetPort: 8080 # 파드의 컨테이너 포트